name: customer-analysis
description: ''
version: 0.0.5
author: michael@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: customeranalysis
  parentArtefactID: michaelprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-11-19 21:54:46'
pipelines:
  pipelines/bronze:
    name: demo_bronze
    description: ''
    author: michael@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-19 21:54:46'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/silver:
    name: demo_silver
    description: Generates a summary of customer orders, including full names, order
      counts, and total amounts. It reads customer and order data from CSV files,
      joins them, and processes the information to provide a ranked list of customers
      based on their total order amounts, limiting the results to the top 25 customers.
    author: michael@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-19 21:56:31'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/demo_gold:
    name: demo_gold
    description: ''
    author: michael@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-12-12 16:25:46'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/top_25
    subgraphs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: ''
    author: michael@prophecy.io
    createdAt: '2024-11-19 21:56:16'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 19010
        datasetType: File
        description: ''
        author: michael@prophecy.io
        createdAt: '2024-11-19 21:56:16'
  datasets/customers:
    name: customers
    description: ''
    author: michael@prophecy.io
    createdAt: '2024-12-06 18:22:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 19010
        datasetType: File
        description: ''
        author: michael@prophecy.io
        createdAt: '2024-12-06 18:22:40'
  datasets/top_25:
    name: top_25
    description: ''
    author: michael@prophecy.io
    createdAt: '2024-12-12 16:24:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 19010
        datasetType: Database
        description: ''
        author: michael@prophecy.io
        createdAt: '2024-12-12 16:24:05'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-19 21:54:46'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-19T21:54:46.576127Z'
  name: plibMaven
  version: 8.8.0
  id: '460735967'
  createdAt: '2024-11-19T21:54:46.576127Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-11-19T21:54:46.576127Z'
  name: plibPypi
  version: 1.9.33
  id: '617167463'
  createdAt: '2024-11-19T21:54:46.576127Z'
  type: plibPypi
  enabled: true
  entity: Project
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-11-19 21:54:31'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.39
    isDefault: true
    author: null
    createdAt: '2024-12-19 16:55:53'
  '32699':
    projectUID: 32699
    projectName: ProphecySparkDataQualityPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/gLsx7fee_project_32699.git&subPath=
    version: 0.0.4
    isDefault: false
    author: null
    createdAt: '2025-02-04 17:49:55'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
