name: customer-analysis
description: ''
version: 0.0.1
author: michael@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: customeranalysis
  parentArtefactID: michaelprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-11-19 21:54:46'
pipelines:
  pipelines/bronze:
    name: bronze
    description: ''
    author: michael@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-19 21:54:46'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/silver:
    name: silver
    description: Generates a summary of sales by customer, combining order and customer
      details. It calculates the total sales and order count for each customer, projecting
      their full names. The results are sorted by total sales, and only the top 25
      customers are retained for final output.
    author: michael@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-19 21:56:31'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers:
    name: customers
    description: ''
    author: michael@prophecy.io
    createdAt: '2024-11-19 21:55:37'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 19010
        datasetType: File
        description: ''
        author: michael@prophecy.io
        createdAt: '2024-11-19 21:55:37'
  datasets/orders:
    name: orders
    description: ''
    author: michael@prophecy.io
    createdAt: '2024-11-19 21:56:16'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 19010
        datasetType: File
        description: ''
        author: michael@prophecy.io
        createdAt: '2024-11-19 21:56:16'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-19 21:54:46'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-19T21:54:46.576127Z'
  name: plibMaven
  version: 8.4.0
  id: '460735967'
  createdAt: '2024-11-19T21:54:46.576127Z'
  type: plibMaven
- modifiedAt: '2024-11-19T21:54:46.576127Z'
  name: plibPypi
  version: 1.9.24
  id: '617167463'
  createdAt: '2024-11-19T21:54:46.576127Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-11-19 21:54:31'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.34
    isDefault: true
    author: null
    createdAt: '2024-11-19 21:54:31'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
